openapi: "3.0.1"
info:
  title: "tasks-api"
  version: "v1.0"
paths:
  /:
    post:
      summary: Create task
      description: Creates a new task
      responses:
        201:
          description: "201 response"
          content: {}
        400:
          description: "400 response"
          content: {}
        500:
          description: "500 response"
          content: {}
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${createCustomerLambdaFunction.Arn}/invocations
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type:
         "aws_proxy"  
