AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is the AWS Lambda functions
Parameters:

  Environment:
    Type: String
    Description: This key is used for environment. It will be used in one of the prefix for  resource names. This also can be passed thru sam deploy


  UniqueName: 
    Type: String 
    Description: Prefix for any resource passed from sam deploy. It will be in the format of mwdet-ecom-x



Resources:

  customerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode : PAY_PER_REQUEST
      TableName: !Sub ${UniqueName}-${Environment}-customers


  createCustomerLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: customerDynamoDBTable
    Properties:
      Handler: index.handler
      CodeUri: "./lambdas/createcustomer/src"
      FunctionName: !Sub ${UniqueName}-${Environment}-create-customer
      Description: create customer data 
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          TABLE_NAME: !Ref customerDynamoDBTable
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !GetAtt customerDynamoDBTable.Arn
      Events: 
        Post: 
          Type: Api
          Properties: 
            RestApiId: !Ref RestApi 
            Path: /
            Method: POST

  RestApi: 
    Type: AWS::Serverless::Api
    Properties: 
      Name: !Sub ${UniqueName}-customer
      StageName : !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:  's3://mwdet-ecom-18-pipeline-artifacts/swagger.yaml'
              # Fn::Join: 
              #   - ''
              #   - -'s3://'
              #     - 'mwdet-ecom-18'
              #     - '-pipeline-artifacts'
              #     - '/swagger1.yaml'
                # !sub s3://${UniqueName}-pipeline-artifacts/swagger.yaml